[#3] 로그인 기능 구현
f-lab-edu/fit-withme pull request #4
Opened 2024-05-22 17:30 UTC by iridescent-hy

2024-05-24 15:34 UTC, blue000927 requested changes

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +    }
롬복을 사용하여 생성자를 생략하면 어떨까요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +        }
DTO에서 Spring @Valid를 사용하여 예외 처리를 presentation 계층에서 수행하면 어떨까요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +        //아이디 존재 확인
요런 주석은 제거해 주시고, 코드만으로 어떻게 동작하는지 알수 있게 해주세요!

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/presentation/dto/request/UserRequest.java
> +//    private String phone;
요거는 왜 주석으로 해 두셨나요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        System.out.println("AccessToken:" + accessToken);
System.out.println()을 사용하면 어떠한 문제점이 있나요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +        //비밀번호 확인
주석 제거

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/infrastructure/dao/UserDao.java
> +public class UserDao {
DB Table 스키마도 추가해주세요!

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/infrastructure/dao/UserDao.java
> +    public User findById(String loginId) {
loginId말고 그냥 id로 해도 되지 않을까요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/domain/model/User.java
> +public record User(String userId, String userName, String userPassword, String email, String phone) {
PK는 어떻게 하실 생각 이신가요? userId는 그 loginId 같은데, 별개의 id를 두시나요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        String accessToken = request.getHeader("ACCESS_TOKEN");
상수로 빼면 어떨까요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        String refreshToken = request.getHeader("REFRESH_TOKEN");
상수로 빼면 어떨까요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        response.setHeader("msg", "Check the tokens.");
msg가 필요한 이유가 뭔가요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/resources/application.yml
> +  refreshTokenValidity: 7200
시크릿이 노출되면 어떠한 문제점이 있을까요?

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/jwt/JwtUtil.java
> +    //유효한 토큰인지 확인
주석 제거

2024-05-24 15:34 UTC, blue000927 commented on src/main/java/com/example/fitwithme/presentation/dto/response/UserResponse.java
> +
들여쓰기 한 줄 제거

2024-05-28 04:21 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +    }
롬복의 @RequiredArgsConstructor 어노테이션을 사용해서 생성자를 자동 생성하도록 수정했습니다

2024-05-28 06:52 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +        }
UserRequest.login 클래스에 @NotBlank 어노테이션을 추가하고 ExceptionAdvice 클래스에 MethodArgumentNotValidException예외를 처리하는 handleValidationExceptions메서드를 추가해서 수정했습니다

2024-05-28 06:53 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +        //아이디 존재 확인
주석 제거했습니다

2024-05-28 06:53 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/presentation/dto/request/UserRequest.java
> +//    private String phone;
여기도 필요없는 부분이라 삭제했습니다!

2024-05-28 06:59 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        System.out.println("AccessToken:" + accessToken);
System.out.println()을 사용하면 이 클래스는 블로킹 i/o인데 동기화까지 동작되기 때문에 작업이 느려질 수 있다는 문제가 있어서 삭제했습니다

2024-05-28 08:32 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +        //비밀번호 확인
주석 제거했습니다!

2024-05-28 08:38 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/infrastructure/dao/UserDao.java
> +    public User findById(String loginId) {
id로 수정했습니다 파라미터 이름 최대한 간결하게 써보도록 하겠습니다!

2024-05-29 01:18 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/domain/model/User.java
> +public record User(String userId, String userName, String userPassword, String email, String phone) {
PK는 아이디 중복이 안되니까 아이디로 하려고 합니다! 아이디는 userId로 통일해서 사용하겠습니다

2024-05-29 01:20 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/jwt/JwtUtil.java
> +    //유효한 토큰인지 확인
주석 제거했습니다!

2024-05-29 01:21 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/presentation/dto/response/UserResponse.java
> +
한 줄 제거했습니다!

2024-05-29 02:47 UTC, iridescent-hy commented on src/main/resources/application.yml
> +  refreshTokenValidity: 7200
애플리케이션 설정 파일이 유출되면 jwt 토큰을 생성할 때 쓰이는 secret 키가 노출되어 토큰을 위조하거나 탈취할 수 있는 위험이 생깁니다. 그래서 JWT_SECRET_KEY라는 이름의 환경변수로 등록해서 환경 변수를 참조하는 방법으로 수정했습니다

2024-05-29 02:56 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        response.setHeader("msg", "Check the tokens.");
처음엔 디버깅 용으로 추가해두긴 했지만 이 부분이 없어도 기능상으로는 문제가 없다고 생각해 삭제했습니다!

2024-05-29 04:36 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        String accessToken = request.getHeader("ACCESS_TOKEN");
TokenType이라는 상수클래스 만들어 수정했습니다

2024-05-29 04:36 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        String refreshToken = request.getHeader("REFRESH_TOKEN");
TokenType이라는 상수클래스 만들어 수정했습니다

2024-05-30 00:31 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/infrastructure/dao/UserDao.java
> +public class UserDao {
schema.sql 파일로 추가했습니다!

2024-05-30 13:13 UTC, blue000927 commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +
요런 무의미한 \n들이 군데군데 있는데 전체적으로 체크하셔서 포맷팅 이쁘게 쫙 해주세요~

2024-05-30 13:13 UTC, blue000927 commented on src/main/java/com/example/fitwithme/common/enums/TokenType.java
> +    REFRESH_TOKEN("REFRESH_TOKEN");       // Task 수행 정보관리
해당 주석이 필요한 이유가 무엇인가요?
액세스 토큰은 "프로젝트 기본 정보 관리"에만 쓰이고, 리프레시 토큰은 "Task 수행 정보 관리"에만 쓰인다는 것인지 궁금합니다.

2024-05-30 13:13 UTC, blue000927 commented on src/main/java/com/example/fitwithme/domain/model/User.java
> +public record User(String userId, String userName, String userPassword, String email, String phone) {
MySQL의 InnoDB는 기본적으로 클러스터 인덱스를 사용하고 있는데, PK를 generate id를 할 때와 userId를 할 때 성능 차이를 혹시 알고 계실까요?

2024-05-30 13:13 UTC, blue000927 commented on src/main/java/com/example/fitwithme/jwt/JwtUtil.java
> +    //토큰생성
주석 제거

2024-05-30 13:13 UTC, blue000927 commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        }
액세스 토큰이 만료되면 리프레시 토큰으로 액세스 토큰 갱신을 해야하지 않을까요?

2024-06-01 16:43 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/domain/model/User.java
> +public record User(String userId, String userName, String userPassword, String email, String phone) {
PK를 generate id를 할 때 레코드가 순차적으로 저장되고 관리되기 때문에 검색이나 삽입 성능이 더 빠른 것 같습니다! id를 PK로 수정해서 하는 게 전체적인 성능을 높이는 것 같습니다

2024-06-01 16:50 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/application/service/UserService.java
> +
전체적으로 다시 정리했습니다!

2024-06-01 16:52 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/common/enums/TokenType.java
> +    REFRESH_TOKEN("REFRESH_TOKEN");       // Task 수행 정보관리
코드 참고하는 과정에서 가져온 것 같은 부분이라 삭제했습니다

2024-06-01 16:52 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/jwt/JwtUtil.java
> +    //토큰생성
주석 제거했습니다!

2024-06-01 17:00 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        }
아 그 부분을 추가했어야 했는데 까먹고 있었습니다! JwtInterceptor 에 else로 엑세스 토큰이 만료되었을 경우의 로직을 추가했고 갱신하는 메서드는 JwtUtil 에 구현했습니다

2024-06-02 05:35 UTC, blue000927 approved these changes
실제로 auto-increment 방식으로 insert가 잘되는지 테스트해봐주세요!

2024-06-02 05:35 UTC, blue000927 commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        }else {
스페이스바 한 칸 추가

2024-06-02 05:35 UTC, blue000927 commented on src/main/resources/mapper/UserMapper.xml
> +      )
id가 아니라 user_id여야 하지 않나요?

2024-06-02 06:48 UTC, iridescent-hy commented on src/main/java/com/example/fitwithme/jwt/JwtInterceptor.java
> +        }else {
추가 했습니다!

2024-06-02 07:03 UTC, iridescent-hy commented on src/main/resources/mapper/UserMapper.xml
> +      )
xml 부분은 아직 수정하지 않은 부분이라 삭제하고 다음 기능 커밋 때 맞게 수정할 계획입니다!

2024-06-02 07:36 UTC, merged